apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nginx.fullname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nginx.fullname" . }}
    spec:
      # initContainer copies the rendered ConfigMap index.html into the PVC once
      initContainers:
      - name: init-copy-index
        image: busybox:1.36
        command:
          - sh
          - -c
          - |
            set -eu
            mkdir -p /work
            cp /config/index.html /work/index.html
        volumeMounts:
          - name: index-config
            mountPath: /config
          - name: html-volume
            mountPath: /work

      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.service.targetPort }}
        volumeMounts:
          - name: html-volume
            mountPath: /usr/share/nginx/html

      volumes:
        - name: index-config
          configMap:
            name: {{ include "nginx.fullname" . }}-index
            items:
              - key: index.html
                path: index.html
        - name: html-volume
          persistentVolumeClaim:
            claimName: {{ include "nginx.fullname" . }}-pvc

