apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-env.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "nginx-env.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "nginx-env.name" . }}
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: {{ include "nginx-env.fullname" . }}-index
