apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-env.fullname" . }}-svc
spec:
  selector:
    app: {{ include "nginx-env.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}
