replicaCount: 3

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  targetPort: 80
  nodePort: 32080
  protocol: TCP

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: ""

env:
  name: staging
  debug: false
  logLevel: INFO
  externalEndpoint: "https://staging.company.com/api"
  clientId: "staging_client"
  cacheTTL: 600
  prefix: "staging"

